### PR TITLE
fix test case

### LINKED ISSUE #77: [Bug]Memory Leak in Future_chain benchmark
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen
Run benchmark on debug mode, there will be memory leaks error from LeakSanitizer:

```
==63002==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 888 byte(s) in 111 object(s) allocated from:
    #0 0x5d7228 in operator new(unsigned long) (/home/admin/code/async_simple/build/benchmarks/benchmarking+0x5d7228)
    #1 0x11de2eb in __gnu_cxx::new_allocator<int>::allocate(unsigned long, void const*) /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/ext/new_allocator.h:114:27
    #2 0x11de290 in std::allocator_traits<std::allocator<int> >::allocate(std::allocator<int>&, unsigned long) /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/alloc_traits.h:444:20
    #3 0x11dddff in std::_Vector_base<int, std::allocator<int> >::_M_allocate(unsigned long) /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/stl_vector.h:343:20
    #4 0x11dd3d9 in void std::vector<int, std::allocator<int> >::_M_realloc_insert<int const&>(__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, int const&) /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/vector.tcc:440:33
    #5 0x11dd0b4 in std::vector<int, std::allocator<int> >::push_back(int const&) /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/stl_vector.h:1195:4
    #6 0x11d2425 in Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(int)::operator()(int) const /home/admin/code/async_simple/benchmarks/Future.bench.cpp:38:19
    #7 0x11d365f in Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&)::operator()(async_simple::Try<int>&&) const /home/admin/code/async_simple/benchmarks/Future.bench.cpp:48:26
    #8 0x11d45ce in std::enable_if<async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&)>::ReturnsFuture::value, async_simple::Future<async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&)>::ReturnsFuture::Inner> >::type async_simple::Future<int>::thenImpl<Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&), async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&)> >(Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&)&&)::'lambda'(async_simple::Try<int>&&)::operator()(async_simple::Try<int>&&) /home/admin/code/async_simple/async_simple/Future.h:256:35
    #9 0x11d4459 in void async_simple::FutureState<int>::setContinuation<std::enable_if<async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&)>::ReturnsFuture::value, async_simple::Future<async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&)>::ReturnsFuture::Inner> >::type async_simple::Future<int>::thenImpl<Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&), async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&)> >(Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&)&&)::'lambda'(async_simple::Try<int>&&)>(Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&))::'lambda'(async_simple::Try<int>&&)::operator()(async_simple::Try<int>&&) /home/admin/code/async_simple/async_simple/FutureState.h:230:13
    #10 0x11d41c1 in std::_Function_handler<void (async_simple::Try<int>&&), void async_simple::FutureState<int>::setContinuation<std::enable_if<async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&)>::ReturnsFuture::value, async_simple::Future<async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&)>::ReturnsFuture::Inner> >::type async_simple::Future<int>::thenImpl<Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&), async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&)> >(Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&)&&)::'lambda'(async_simple::Try<int>&&)>(Future_chain(benchmark::State&)::$_0::operator()() const::'lambda0'(async_simple::Try<int>&&))::'lambda'(async_simple::Try<int>&&)>::_M_invoke(std::_Any_data const&, async_simple::Try<int>&&) /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/std_function.h:300:2
    #11 0x11e1162 in std::function<void (async_simple::Try<int>&&)>::operator()(async_simple::Try<int>&&) const /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/std_function.h:688:14
    #12 0x11debcc in async_simple::FutureState<int>::scheduleContinuation(bool) /home/admin/code/async_simple/async_simple/FutureState.h:271:13
    #13 0x11df64f in async_simple::FutureState<int>::setResult(async_simple::Try<int>&&) /home/admin/code/async_simple/async_simple/FutureState.h:215:21
    #14 0x11df41c in async_simple::Promise<int>::setValue(async_simple::Try<int>&&) /home/admin/code/async_simple/async_simple/Promise.h:106:23
    #15 0x11d2c5a in std::enable_if<!(async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(async_simple::Try<int>&&)>::ReturnsFuture::value), async_simple::Future<async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(async_simple::Try<int>&&)>::ReturnsFuture::Inner> >::type async_simple::Future<int>::thenImpl<Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(async_simple::Try<int>&&), async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(async_simple::Try<int>&&)> >(Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(async_simple::Try<int>&&)&&)::'lambda'(async_simple::Try<int>&&)::operator()(async_simple::Try<int>&&) /home/admin/code/async_simple/async_simple/Future.h:291:23
    #16 0x11d2b19 in void async_simple::FutureState<int>::setContinuation<std::enable_if<!(async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(async_simple::Try<int>&&)>::ReturnsFuture::value), async_simple::Future<async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(async_simple::Try<int>&&)>::ReturnsFuture::Inner> >::type async_simple::Future<int>::thenImpl<Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(async_simple::Try<int>&&), async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(async_simple::Try<int>&&)> >(Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(async_simple::Try<int>&&)&&)::'lambda'(async_simple::Try<int>&&)>(Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(async_simple::Try<int>&&))::'lambda'(async_simple::Try<int>&&)::operator()(async_simple::Try<int>&&) /home/admin/code/async_simple/async_simple/FutureState.h:230:13
    #17 0x11d2881 in std::_Function_handler<void (async_simple::Try<int>&&), void async_simple::FutureState<int>::setContinuation<std::enable_if<!(async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(async_simple::Try<int>&&)>::ReturnsFuture::value), async_simple::Future<async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(async_simple::Try<int>&&)>::ReturnsFuture::Inner> >::type async_simple::Future<int>::thenImpl<Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(async_simple::Try<int>&&), async_simple::TryCallableResult<int, Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(async_simple::Try<int>&&)> >(Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(async_simple::Try<int>&&)&&)::'lambda'(async_simple::Try<int>&&)>(Future_chain(benchmark::State&)::$_0::operator()() const::'lambda'(async_simple::Try<int>&&))::'lambda'(async_simple::Try<int>&&)>::_M_invoke(std::_Any_data const&, async_simple::Try<int>&&) /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/std_function.h:300:2
    #18 0x11e1162 in std::function<void (async_simple::Try<int>&&)>::operator()(async_simple::Try<int>&&) const /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/std_function.h:688:14
    #19 0x11e2279 in async_simple::FutureState<int>::scheduleContinuation(bool)::'lambda'()::operator()() /home/admin/code/async_simple/async_simple/FutureState.h:282:29
    #20 0x11e1f4c in std::_Function_handler<void (), async_simple::FutureState<int>::scheduleContinuation(bool)::'lambda'()>::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/std_function.h:300:2
    #21 0x7f2883f41602 in std::function<void ()>::operator()() const /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/std_function.h:688:14
    #22 0x7f2883f4b254 in async_simple::util::WorkItem::process() /home/admin/code/async_simple/async_simple/util/ThreadPool.h:141:22
    #23 0x7f2883f48cdf in async_simple::util::ThreadPool::workerLoop(unsigned long) /home/admin/code/async_simple/async_simple/util/ThreadPool.h:381:19
    #24 0x7f2883f4c676 in void std::__invoke_impl<void, void (async_simple::util::ThreadPool::*&)(unsigned long), async_simple::util::ThreadPool*&, unsigned long&>(std::__invoke_memfun_deref, void (async_simple::util::ThreadPool::*&)(unsigned long), async_simple::util::ThreadPool*&, unsigned long&) /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/invoke.h:73:14
    #25 0x7f2883f4c4b6 in std::__invoke_result<void (async_simple::util::ThreadPool::*&)(unsigned long), async_simple::util::ThreadPool*&, unsigned long&>::type std::__invoke<void (async_simple::util::ThreadPool::*&)(unsigned long), async_simple::util::ThreadPool*&, unsigned long&>(void (async_simple::util::ThreadPool::*&)(unsigned long), async_simple::util::ThreadPool*&, unsigned long&) /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/invoke.h:95:14
    #26 0x7f2883f4c3f3 in void std::_Bind<void (async_simple::util::ThreadPool::* (async_simple::util::ThreadPool*, unsigned long))(unsigned long)>::__call<void, 0ul, 1ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul>) /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/functional:400:11
    #27 0x7f2883f4c25d in void std::_Bind<void (async_simple::util::ThreadPool::* (async_simple::util::ThreadPool*, unsigned long))(unsigned long)>::operator()<void>() /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/functional:482:17
    #28 0x7f2883f4c16c in void std::__invoke_impl<void, std::_Bind<void (async_simple::util::ThreadPool::* (async_simple::util::ThreadPool*, unsigned long))(unsigned long)> >(std::__invoke_other, std::_Bind<void (async_simple::util::ThreadPool::* (async_simple::util::ThreadPool*, unsigned long))(unsigned long)>&&) /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/invoke.h:60:14
    #29 0x7f2883f4c0fc in std::__invoke_result<std::_Bind<void (async_simple::util::ThreadPool::* (async_simple::util::ThreadPool*, unsigned long))(unsigned long)> >::type std::__invoke<std::_Bind<void (async_simple::util::ThreadPool::* (async_simple::util::ThreadPool*, unsigned long))(unsigned long)> >(std::_Bind<void (async_simple::util::ThreadPool::* (async_simple::util::ThreadPool*, unsigned long))(unsigned long)>&&) /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/invoke.h:95:14

SUMMARY: AddressSanitizer: 888 byte(s) leaked in 111 allocation(s).
```
### Reproduction way
Run benchmark on debug mode.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by qicosmos**
## Why

Closes #77

### CODE REVIEW

File: async_simple/coro/test/LazyTest.cpp [hunk 1]
```diff
@@ -1351,15 +1351,13 @@ TEST_F(LazyTest, testBatchedcollectAll) {
...
-        test1().via(&e1).detach();
-    }
-
+    executors::SimpleExecutor e1(1);
+    auto test1 = [&count]() -> Lazy<int> {
+        count += 2;
+        co_return count;
+    };
+    test1().via(&e1).detach();
+    std::this_thread::sleep_for(1s);
```
Comment (ChuanqiXu9) [inline async_simple/coro/test/LazyTest.cpp:1360]: It is not good to sleep to wait for it gets done.

The general solution is to wrap this one into something like future we could wait.

**Review by ChuanqiXu9 — APPROVED** [review]
LGTM.
